language: java
rvm:
 - 2.2
 - jruby
  jobs:
  
  include:
    - stage: test
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy
